name: Build and Test

on: [pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull Docker Image
        run: docker pull rpgillespie6/fastcov
      - name: Run Tests
        run: docker run -v "$PWD":/mnt/workspace -w /mnt/workspace rpgillespie6/fastcov bash -c "cd ./test && ./run_tests.sh"
      - name: Upload Coverage
        run: bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy -f test/functional/cmake_project/build/coverage.xml -f test/unit/coverage.xml
        